---
- name: Playbook with Multiple Prompts
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "db_user"
      prompt: "Enter the database username"
      private: no

    - name: "db_password"
      prompt: "Enter the database password"
      private: yes

  tasks:
    - name: Create a database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present
