---
- hosts: all
  become: yes

  tasks:
    - name: Ensure facts.d directory exists
      file:
        path: /etc/ansible/facts.d
        state: directory
        mode: '0755'

    - name: Create custom fact file
      copy:
        dest: /etc/ansible/facts.d/custom.fact
        content: |
          [localfact]
          environment=production
          application=myapp
        mode: '0644'
