---
- hosts: all
  become: yes

  tasks:
    - name: Gather facts
      setup:
        filter: ansible_local

    - name: Debug custom facts
      debug:
        msg: "Environment: {{ ansible_local.custom.localfact.environment }}, Application: {{ ansible_local.custom.localfact.application }}"

    - name: Perform task based on custom fact
      debug:
        msg: "This task runs in the production environment for the myapp application"
      when: ansible_local.custom.localfact.environment == 'production' and ansible_local.custom.localfact.application == 'myapp'