---
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
  - name: Update package lists.
    apt:
      #update_cache: yes

  - name: Upgrade packages.
    apt:
      upgrade: dist
      autoclean: yes

  - name: Install software initial.
    apt:
      name:  software-properties-common
      state: present

  - name: Stop ufw  service.
    ufw:
      name: ufw
      state: disabled

  - name: Install NVM
    shell: |
      wget -q -O- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install node
    args:
      executable: /bin/bash
  
  - name: Check node version.
    shell: /root/.nvm/versions/node/v22.2.0/bin/node -v
    args:
      executable: /bin/bash
    register: node_version_output  

  - name: Show node version.
    debug:
      msg: "Node.js version installed: {{ node_version_output.stdout }}"

  - name: Ensure Node.js app folder exists.
    file:
      path: "{{node_apps_location}}"
      state: directory

  - name: Copy example Node.js app to server. 
    copy:
      src: /home/jabj/ansible/assets/app
      dest: "{{node_apps_location}}"

  - name: Install app dependencies defined in package.json.
    shell: | 
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      cd "{{node_apps_location}}"/app
      npm install
    args:
      executable: /bin/bash  

  - name: Create systemd service file for Node.js API
    copy:
      dest: /etc/systemd/system/nodeapi.service
      content: |
        [Unit]
        Description=Node.js API

        [Service]
        ExecStart=/root/.nvm/versions/node/{{ node_version_output.stdout }}/bin/node /usr/local/opt/node/app/app.js
        Restart=always
        User=root
        Environment=PATH=/root/.nvm/versions/node/{{ node_version_output.stdout }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        Environment=NODE_ENV=production
        WorkingDirectory=/usr/local/opt/node/app/

        [Install]
        WantedBy=multi-user.target


  - name: Reload systemd to recognize the new service
    systemd:
      daemon_reload: yes    

  - name: Enable and start Node.js API service
    systemd:
      name: nodeapi
      enabled: yes
      state: started
